#!/bin/bash
COMPOSE_FILE="docker-compose.yml"

cd "${BASH_SOURCE[0]%/*}/.."

# remove images and container
docker-compose -f $COMPOSE_FILE down --rmi local --volumes --remove-orphans
# build from scratch
docker-compose -f $COMPOSE_FILE pull && \
    docker-compose -f $COMPOSE_FILE build --pull && \
    docker-compose -f $COMPOSE_FILE up -d --force-recreate